# Generated by Django 2.2.2 on 2020-05-14 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='data',
        ),
        migrations.AddField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
