# Generated by Django 2.2.2 on 2020-05-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_readed_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
